apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: webnet
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              webnet: "true"
  podSelector:
    matchLabels:
      webnet: "true"
