apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: webserver
  name: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      service: webserver
  strategy: {}
  template:
    metadata:
      labels:
        network/webnet: "true"
        service: webserver
    spec:
      containers:
        - image: winedup/hellowhale:live
          name: webserver
          ports:
            - containerPort: 80
          resources: {}
      hostname: webserver
      restartPolicy: Always
status: {}
